//
//  problem2.hpp
//  Projecteuler
//
//  Created by Shi Yue on 9/4/2016.
//  Copyright © 2016 Shi Yue. All rights reserved.
//

#ifndef problem2_hpp
#define problem2_hpp

#include <stdio.h>

#endif /* problem2_hpp */

//=========================== Problem 2 ===========================
//Title: Even Fibonacci numbers
/*
 Start date: 3/24/2016
 Finish date: 3/24/2016
 
 Description:
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 
 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

void run_problem2();